from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.sql import func

from app.db.base import Base


class ChallengeOutput(Base):
    """
    An adversarial observation or question about one or more Claims,
    generated by the Challenger. This is NOT a Claim and must never be
    treated as one - it critiques reasoning, it does not assert anything
    about the world, and it must never contain investment advice or a
    recommended decision.
    """

    __tablename__ = "challenge_outputs"

    id = Column(Integer, primary_key=True, index=True)

    research_case_id = Column(
        Integer, ForeignKey("research_cases.id"), nullable=False, index=True
    )

    category = Column(String, nullable=False)
    text = Column(String, nullable=False)

    created_at = Column(DateTime, server_default=func.now())


class ChallengeOutputClaim(Base):
    """
    Link table between a ChallengeOutput and the Claims it references.
    A challenge may reference multiple claims; a claim may be referenced
    by multiple challenges. This is a plain relational link, not a JSON
    column on ChallengeOutput.
    """

    __tablename__ = "challenge_output_claims"

    id = Column(Integer, primary_key=True, index=True)

    challenge_output_id = Column(
        Integer, ForeignKey("challenge_outputs.id"), nullable=False, index=True
    )
    claim_id = Column(Integer, ForeignKey("claims.id"), nullable=False, index=True)